[package]
name = "basic-ciphers-cxxqt"
version = "1.0.0"
edition = "2021"
authors = ["KauÃª Miziara"]
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
cxx-qt = "0.4"
cxx-qt-lib = "0.4"

[build-dependencies]
cxx-qt-build = "0.4"
